training_pipeline_config:
  pipeline_name : cement_strength
  artifact_dir : artifact

data_ingestion_config:
  dataset_download_url : https://archive.ics.uci.edu/static/public/165/concrete+compressive+strength.zip
  raw_data_dir : raw_data
  zip_data_dir : zip_data
  ingested_dir : ingested_data
  ingested_train_dir : train
  ingested_test_dir : test


data_validation_config:
  scheme_dir : config
  schema_file : schema.yaml
  report_page_file_name : report.html

data_transformation_config:
  graph_save_dir : graph_data
  train_dir : train
  test_dir : test
  preprocessed_object_dir : preprocessed
  preprocessed_object_file_name : preprocessed.pkl
  cluster_model_dir : cluster_model
  cluster_model_file_name : cluster_model.pkl

model_trainer_config:
  model_file_name : model.pkl
  base_accuracy : 0.6
  model_config_dir : config
  model_config_file_name : model.yaml


model_evalution_config:
  model_evulation_file_name : model_evulation.yaml




  