training_pipeline_config:
  pipeline_name : cement_strength
  artifact_dir : artifact

data_ingestion_config:
  dataset_download_url : https://archive.ics.uci.edu/static/public/165/concrete+compressive+strength.zip
  raw_data_dir : raw_data
  zip_data_dir : zip_data
  ingested_dir : ingested_data
  ingested_train_dir : train
  ingested_test_dir : test


data_validation_config:
  scheme_dir : config
  schema_file : schema.yaml
  report_page_file_name : report.html